// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package params

// #DeskConfig — desk.yml. Closed: an unknown key is an error, not a shrug.
type DeskConfig struct {
	Profile string `json:"profile"`

	Topic string `json:"topic"`

	Cutoff string `json:"cutoff"`

	Select int64 `json:"select,omitempty"`

	Minutes int64 `json:"minutes,omitempty"`

	Audio bool `json:"audio,omitempty"`

	Out string `json:"out"`

	Cast map[string]string `json:"cast"`
}

type Resolver string

// #Source — one RESOLVED source. `digest` is mandatory: a source without a digest is not a receipt.
type Source struct {
	Id string `json:"id"`

	Resolver Resolver `json:"resolver"`

	Ref string `json:"ref"`

	Digest string `json:"digest"`

	Bytes int64 `json:"bytes"`

	Repo string `json:"repo,omitempty"`

	Calver string `json:"calver,omitempty"`

	Path string `json:"path,omitempty"`

	Title string `json:"title,omitempty"`

	Body string `json:"body,omitempty"`
}

type TagGap struct {
	Repo string `json:"repo"`

	Tag string `json:"tag"`

	Calver string `json:"calver"`
}

// #SourceBundle — recorded with the episode; the bundle is the record, never the query.
type SourceBundle struct {
	Cutoff string `json:"cutoff"`

	Generated_at string `json:"generated_at"`

	Repos_scanned int64 `json:"repos_scanned"`

	Repos_with_entries int64 `json:"repos_with_entries"`

	// At least one source, or the run is refused (§5.4). MEASURED: this needs the PREFIX-list form.
	// `[...#Source]` alone accepts `[]`; `[...#Source] & [_, ...]` rejects it but INLINES an anonymous
	// struct, so Go callers cannot pass []params.Source; and a hidden `_min: len(entries) >= 1` is a
	// no-op -- the comparison evaluates to the boolean VALUE false, which CUE accepts, so nothing fails.
	// `[#Source, ...#Source]` rejects `[]` AND generates `[]Source`.
	Entries []Source `json:"entries"`

	Tag_gaps []TagGap `json:"tag_gaps"`
}

type Beat string

type Unlock string

type HonestLimit string

type Segment struct {
	Title string `json:"title"`

	Mechanism string `json:"mechanism"`

	Receipt Beat `json:"receipt"`

	Receipt_source string `json:"receipt_source"`

	Unlock Unlock `json:"unlock"`

	Honest_limit HonestLimit `json:"honest_limit"`

	Comic_beat string `json:"comic_beat"`
}

type Episode struct {
	Front_matter struct {
		Episode string `json:"episode"`

		Topic string `json:"topic"`

		Profile string `json:"profile"`

		Cutoff string `json:"cutoff"`

		Cast map[string]struct {
			Sid int64 `json:"sid"`

			Voice string `json:"voice"`
		} `json:"cast"`

		Sources int64 `json:"sources"`

		Coverage Coverage `json:"coverage"`

		Gaps []string `json:"gaps"`
	} `json:"front_matter"`

	Cold_open string `json:"cold_open"`

	// The floor is THREE segments, in the prefix-list form (see source.cue's MEASURED note: a hidden
	// `_min: len(segments) >= 3` is inert, and `[...#Segment] & [_, _, _]` destroys the Go element type).
	// The CEILING of five cannot be expressed without an inline element type, so it is enforced in Go
	// (Emit) -- a type-inexpressible remainder, guarded where the episode is actually consumed.
	Segments []Segment `json:"segments"`

	Pinch struct {
		Claim string `json:"claim"`

		Citation string `json:"citation"`
	} `json:"pinch"`

	Close string `json:"close"`
}

type Coverage struct {
	Selected int64 `json:"selected"`

	Skipped int64 `json:"skipped"`

	Repos_scanned int64 `json:"repos_scanned"`

	Repos_used int64 `json:"repos_used"`
}

// #Claim — one sentence of the script and the receipt under it. `quote` must appear VERBATIM in the
// source named by `source_id`; that cross-reference is the one check a type cannot express, so the Go
// gate in validate.go owns it (C4: the anti-fabrication gate).
type Claim struct {
	Claim_id string `json:"claim_id"`

	Source_id string `json:"source_id"`

	Quote string `json:"quote"`
}

// #TypedOutputs — the writing stage's output as ONE unit (§13.8): all four blocks are required, so a
// missing block is a validation failure rather than a silent omission. `script` is emitted from
// #Episode; `sources`/`coverage`/`gaps` are the provenance the episode publishes.
type TypedOutputs struct {
	Script string `json:"script"`

	Sources []Claim `json:"sources"`

	Coverage Coverage `json:"coverage"`

	Gaps []string `json:"gaps"`
}

type RenderManifest struct {
	Renderer string `json:"renderer"`

	Source string `json:"source"`

	Output_wav string `json:"output_wav"`

	Output_m4a string `json:"output_m4a"`

	Voices map[string]struct {
		Sid int64 `json:"sid"`

		Voice string `json:"voice"`
	} `json:"voices"`

	Total_duration_s any/* CUE number; int64 or float64 */ `json:"total_duration_s"`

	Segments []struct {
		Index int64 `json:"index"`

		Kind string `json:"kind"`

		Sid int64 `json:"sid,omitempty"`

		Voice string `json:"voice,omitempty"`

		Duration_s any/* CUE number; int64 or float64 */ `json:"duration_s"`

		Text string `json:"text,omitempty"`
	} `json:"segments"`
}
