// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package params

// #DeskConfig — desk.yml. Closed: an unknown key is an error, not a shrug.
type DeskConfig struct {
	Profile string `json:"profile"`

	Topic string `json:"topic"`

	Cutoff string `json:"cutoff"`

	Select int64 `json:"select,omitempty"`

	Minutes int64 `json:"minutes,omitempty"`

	Audio bool `json:"audio,omitempty"`

	Out string `json:"out"`

	Cast map[string]string `json:"cast"`
}

type Resolver string

// #Source — one RESOLVED source. `digest` is mandatory: a source without a digest is not a receipt.
type Source struct {
	Id string `json:"id"`

	Resolver Resolver `json:"resolver"`

	Ref string `json:"ref"`

	Digest string `json:"digest"`

	Bytes int64 `json:"bytes"`

	Repo string `json:"repo,omitempty"`

	Calver string `json:"calver,omitempty"`

	Path string `json:"path,omitempty"`

	Title string `json:"title,omitempty"`

	Body string `json:"body,omitempty"`
}

type TagGap struct {
	Repo string `json:"repo"`

	Tag string `json:"tag"`

	Calver string `json:"calver"`
}

// #SourceBundle — recorded with the episode; the bundle is the record, never the query.
type SourceBundle struct {
	Cutoff string `json:"cutoff"`

	Generated_at string `json:"generated_at"`

	Repos_scanned int64 `json:"repos_scanned"`

	Repos_with_entries int64 `json:"repos_with_entries"`

	Entries []struct {
		Id string `json:"id"`

		Resolver Resolver `json:"resolver"`

		Ref string `json:"ref"`

		Digest string `json:"digest"`

		Bytes int64 `json:"bytes"`

		Repo string `json:"repo,omitempty"`

		Calver string `json:"calver,omitempty"`

		Path string `json:"path,omitempty"`

		Title string `json:"title,omitempty"`

		Body string `json:"body,omitempty"`
	} `json:"entries"`

	Tag_gaps []TagGap `json:"tag_gaps"`
}

type Beat string

type Unlock string

type HonestLimit string

type Segment struct {
	Title string `json:"title"`

	Mechanism string `json:"mechanism"`

	Receipt Beat `json:"receipt"`

	Receipt_source string `json:"receipt_source"`

	Unlock Unlock `json:"unlock"`

	Honest_limit HonestLimit `json:"honest_limit"`

	Comic_beat string `json:"comic_beat"`
}

type Episode struct {
	Front_matter struct {
		Episode string `json:"episode"`

		Topic string `json:"topic"`

		Profile string `json:"profile"`

		Cutoff string `json:"cutoff"`

		Cast map[string]struct {
			Sid int64 `json:"sid"`

			Voice string `json:"voice"`
		} `json:"cast"`

		Sources int64 `json:"sources"`

		Coverage Coverage `json:"coverage"`

		Gaps []string `json:"gaps"`
	} `json:"front_matter"`

	Cold_open string `json:"cold_open"`

	Segments []Segment `json:"segments"`

	Pinch struct {
		Claim string `json:"claim"`

		Citation string `json:"citation"`
	} `json:"pinch"`

	Close string `json:"close"`
}

type Coverage struct {
	Selected int64 `json:"selected"`

	Skipped int64 `json:"skipped"`

	Repos_scanned int64 `json:"repos_scanned"`

	Repos_used int64 `json:"repos_used"`
}

type RenderManifest struct {
	Renderer string `json:"renderer"`

	Source string `json:"source"`

	Output_wav string `json:"output_wav"`

	Output_m4a string `json:"output_m4a"`

	Voices map[string]struct {
		Sid int64 `json:"sid"`

		Voice string `json:"voice"`
	} `json:"voices"`

	Total_duration_s any/* CUE number; int64 or float64 */ `json:"total_duration_s"`

	Segments []struct {
		Index int64 `json:"index"`

		Kind string `json:"kind"`

		Sid int64 `json:"sid,omitempty"`

		Voice string `json:"voice,omitempty"`

		Duration_s any/* CUE number; int64 or float64 */ `json:"duration_s"`

		Text string `json:"text,omitempty"`
	} `json:"segments"`
}
